/**
 * pending-images.ts — Simple in-memory queue for images generated by tools
 * that need to be sent via Telegram after the chat turn completes.
 */

export interface PendingImage {
  imageBase64: string;
  caption?: string;
}

const queue: PendingImage[] = [];

/** Push an image to the pending queue (called by tools). */
export function pushPendingImage(image: PendingImage): void {
  queue.push(image);
}

/** Drain all pending images (called by gateway after chat turn). */
export function drainPendingImages(): PendingImage[] {
  return queue.splice(0);
}
